# region ISERO PATCH kb-commission
name: "Commission"
what_is_it: >
  Egyedi képek és videók megrendelése (nem adoptable). A képek magas felbontású PNG-k,
  a videók rövid AI-klippek (több iterációval válogatva). Árazás mennyiségtől és hossz­tól függ.
pricing:
  image:
    unit_usd: 6
    bulk_discount:
      min_qty: 4
      off_per_item_usd: 1
  video:
    price_per_5s_usd: 20
    bulk_discount:
      min_videos: 4
      off_per_video_usd: 5
  packages:
    - name: "SFX Avatar video"
      from_usd: 49.99
    - name: "Influencer/model (pose/lipsync/dance)"
      from_usd: 79.99
      to_usd: 129.99
    - name: "Product promo (script+logo+closeups)"
      from_usd: 149.99
      to_usd: 249.99
facts:
  - "Kép: nagy felbontású PNG, prompt jegyzet kérhető."
  - "Videó: 5 mp-es egységekben számolunk a minőség miatt."
  - "Alap átfutás ≈ 3 nap (sorfüggő)."
objections:
  - cue: "drága|expensive|too much"
    say: "A jó minőséghez iterációk kellenek — ez benne van az árban; 4+ tételnél automatikus kedvezmény jár."
  - cue: "siet|urgent|rush"
    say: "Megpróbálom előrevenni; jelzek reális céldátumot. Ha több tételt választasz, párhuzamosítok."
closing_lines:
  - "Kezdjünk 2 képpel és 1 rövid (10 mp) klippel — így gyorsan látod a look&feel-t; 4+ tételnél már jön a kedvezmény."
# endregion ISERO PATCH kb-commission
