services:
  - type: worker
    name: isero-discord-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
