services:
  - type: worker
    name: isero-discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
