name: auto-resolve-codex

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

permissions:
  contents: write        # KELL a push-hoz
  pull-requests: write

jobs:
  resolve:
    # csak a Codex által nyitott, "codex/"-szal kezdődő ágra fusson
    if: contains(github.event.pull_request.head.ref, 'codex/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # A "Codex verzió nyer" = PR-branch preferált. Ehhez az -X ours kell,
      # mert most a PR HEAD-jén állunk és a main-t merge-öljük bele.
      - name: Merge main preferring PR branch (ours)
        run: |
          git fetch origin main
          git merge -X ours origin/main --no-edit || true

      - name: Push resolved branch
        run: |
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
